default:
  image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
  - docker:stable-dind

# include:
#   - template: Container-Scanning.gitlab-ci.yml
  
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - base_image
  - dev_images

base_images:
  stage:
    - build
    - base_image
  script:
    - ./scripts/manage.sh build base
    - ./scripts/manage.sh test base
    - ./scripts/manage.sh publish-to-gitlab-registry base

  
dev_images:
  stage:
    - build
    - dev_image
  script:
    - ./scripts/manage.sh build dev
    - ./scripts/manage.sh test dev
    - ./scripts/manage.sh publish-to-gitlab-registry dev
