default:
  image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
services:
  - docker:stable-dind

# include:
#   - template: Container-Scanning.gitlab-ci.yml
  
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - deploy
  - base_image
  - dev_image
  - dev_vscode_image

base_images:
  stage: base_image
  script:
    - ./scripts/manage.sh build base
    - ./scripts/manage.sh test base
    - ./scripts/manage.sh publish-to-gitlab-registry base

  
dev_images:
  stage: dev_image
  script:
    - ./scripts/manage.sh build dev
    - ./scripts/manage.sh test dev
    - ./scripts/manage.sh publish-to-gitlab-registry dev

dev_vscode_images:
  stage: dev_vscode_image
  script:
    - ./scripts/manage.sh build dev-vscode
    - ./scripts/manage.sh test dev-vscode
    - ./scripts/manage.sh publish-to-gitlab-registry dev-vscode
